micronaut:
  application:
    name: hc3MainHeating
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        mapping: '/swagger/**'
        paths: 'classpath:META-INF/swagger'
      swagger-ui:
        mapping: '/swagger-ui/**'
        paths: 'classpath:META-INF/swagger/views/swagger-ui'
# Message Bus configuration - DEV Enviroment
rabbitmq:
  uri: amqp://hc3-werkstatt:5672
# Programm configuration
test: hc-temperature
hc3:
  influxdb:
    url: http://localhost:8086
    username: hc3
    password: hc3
  temperatureQueue:
    name: hc-temperature
  relais-exchange:
    name: hc-relais-hat
  sensor:
    inlet-grey-water-sensor-id: "-"
    greyWaterSensorID: " "
    outletSolarSensorID: " "
    inletHeatingSensorID: " "
    outdoorSensorID: " "
  pump:
    heating:
      relais-id: 2
      switch-on-temp: 45
      min-diff-temp: 5
    main-circuit:
      relais-id: 3
      switch-on-temp: 47
      time-range-from: "05:20"
      time-range-until: "22:10"

      
